#!/bin/bash
# To make the debian package
echo "Version: "
read version
cargo build --release
cp target/release/uniconv uniconv/usr/bin/
dpkg-deb --build uniconv

mv uniconv.deb ~/MKProjects/Packages/uniconv-$version.deb
